apiVersion: 1

datasources:
  - name: TriageIA-Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    user: triageia
    secureJsonData:
      password: triageia
    jsonData:
      database: triageia
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
